#!/usr/bin/env bash

set -euo pipefail

THEME_DIR="$HOME/.config/hypr/themes"
COLORS_CONF="$HOME/.config/hypr/colors.conf"
APPEARANCE_LUA="$HOME/.config/hypr/conf/appearance.lua"
CURRENT_THEME_FILE="$HOME/.cache/hyprland-current-theme"

WAYBAR_STYLE="$HOME/.config/waybar/style.css"
WAYBAR_COLORS="$HOME/.config/waybar/colors.css"
KITTY_CONF="$HOME/.config/kitty/kitty.conf"
KITTY_COLORS="$HOME/.config/kitty/matugen-colors.conf"
ROFI_CONFIG="$HOME/.config/rofi/config.rasi"
ROFI_COLORS="$HOME/.config/rofi/colors.rasi"
GTK3_DIR="$HOME/.config/gtk-3.0"
GTK4_DIR="$HOME/.config/gtk-4.0"
WLOGOUT_STYLE="$HOME/.config/wlogout/style.css"
SWYNC_STYLE="$HOME/.config/swaync/style.css"

mkdir -p "$(dirname "$CURRENT_THEME_FILE")"

# List available themes
list_themes() {
    find "$THEME_DIR" -name "*.conf" -type f | xargs -I {} basename {} .conf | sort
}

# Get current theme
get_current_theme() {
    if [ -f "$CURRENT_THEME_FILE" ]; then
        cat "$CURRENT_THEME_FILE"
    else
        echo "custom"
    fi
}

# Parse color from theme file
parse_color() {
    local var=$1
    local theme_file=$2
    grep "^\\\$$var =" "$theme_file" | sed 's/^[^=]*= //g' | tr -d ' "' || echo "rgba(595959aa)"
}

# Convert Hypr rgba(...) or #rrggbbaa values to plain hex (#rrggbb)
color_hex() {
    local input=${1//[[:space:]]/}
    input=${input#rgba(}
    input=${input%)}
    input=${input#\#}
    if [ "${#input}" -eq 8 ]; then
        input=${input:0:6}
    fi
    printf '#%s' "$input"
}

# Convert Hypr rgba(...) or #rrggbbaa values to hex with alpha (#rrggbbaa)
color_hexalpha() {
    local input=${1//[[:space:]]/}
    input=${input#rgba(}
    input=${input%)}
    input=${input#\#}
    if [ "${#input}" -eq 6 ]; then
        printf '#%sff' "$input"
    else
        printf '#%s' "$input"
    fi
}

write_waybar_theme() {
    mkdir -p "$(dirname "$WAYBAR_COLORS")"
    local background_hex=$(color_hex "$BACKGROUND")
    local surface_hex=$(color_hex "$SURFACE")
    local surface_container_hex=$(color_hex "$SURFACE_CONTAINER")
    local text_hex=$(color_hex "$PRIMARY")
    local readable_text_hex=$(color_hex "$READABLE_TEXT")
    local on_text_hex=$(color_hex "$FOREGROUND")
    local secondary_hex=$(color_hex "$SECONDARY")
    local tertiary_hex=$(color_hex "$TERTIARY")
    local error_hex=$(color_hex "$ERROR")

    cat >"$WAYBAR_COLORS" <<EOF
@define-color background $background_hex;
@define-color surface $surface_hex;
@define-color surface_container $surface_container_hex;
@define-color text $text_hex;
@define-color primary $text_hex;
@define-color readable_text $readable_text_hex;
@define-color on_text $on_text_hex;
@define-color secondary $secondary_hex;
@define-color tertiary $tertiary_hex;
@define-color error $error_hex;
@define-color warning $(color_hex "$WARNING");
@define-color success $(color_hex "$SUCCESS");
@define-color chip $surface_container_hex;
@define-color chip_border $surface_hex;
EOF
}

write_kitty_theme() {
    mkdir -p "$(dirname "$KITTY_COLORS")"
    local background_hex=$(color_hex "$BACKGROUND")
    local foreground_hex=$(color_hex "$FOREGROUND")
    local selection_hex=$(color_hex "$PRIMARY")
    local selection_foreground_hex=$(color_hex "$READABLE_TEXT")
    local cursor_hex=$(color_hex "$PRIMARY")
    local color0_hex=$(color_hex "$BACKGROUND")
    local color1_hex=$(color_hex "$ERROR")
    local color2_hex=$(color_hex "$SUCCESS")
    local color3_hex=$(color_hex "$WARNING")
    local color4_hex=$(color_hex "$PRIMARY")
    local color5_hex=$(color_hex "$SECONDARY")
    local color6_hex=$(color_hex "$TERTIARY")
    local color7_hex=$(color_hex "$FOREGROUND")
    local color8_hex=$(color_hex "$SURFACE")
    local color9_hex=$(color_hex "$ERROR")
    local color10_hex=$(color_hex "$SUCCESS")
    local color11_hex=$(color_hex "$WARNING")
    local color12_hex=$(color_hex "$PRIMARY")
    local color13_hex=$(color_hex "$SECONDARY")
    local color14_hex=$(color_hex "$TERTIARY")
    local color15_hex=$(color_hex "$FOREGROUND")

    cat >"$KITTY_COLORS" <<EOF
# Generated by theme-preset-switcher.sh
background $background_hex
foreground $foreground_hex
selection_background $selection_hex
selection_foreground $selection_foreground_hex
cursor $cursor_hex
cursor_text_color $background_hex
color0 $color0_hex
color1 $color1_hex
color2 $color2_hex
color3 $color3_hex
color4 $color4_hex
color5 $color5_hex
color6 $color6_hex
color7 $color7_hex
color8 $color8_hex
color9 $color9_hex
color10 $color10_hex
color11 $color11_hex
color12 $color12_hex
color13 $color13_hex
color14 $color14_hex
color15 $color15_hex
EOF

    if [ -f "$KITTY_CONF" ] && ! grep -qxF "include matugen-colors.conf" "$KITTY_CONF"; then
        printf '\ninclude matugen-colors.conf\n' >>"$KITTY_CONF"
    fi
}

write_rofi_theme() {
    mkdir -p "$(dirname "$ROFI_COLORS")"
    local background_hex=$(color_hex "$BACKGROUND")
    local surface_hex=$(color_hex "$SURFACE")
    local readable_text_hex=$(color_hex "$READABLE_TEXT")
    local accent_hex=$(color_hex "$PRIMARY")
    local on_accent_hex=$(color_hex "$FOREGROUND")
    local error_hex=$(color_hex "$ERROR")

    cat >"$ROFI_COLORS" <<EOF
* {
    matugen-background: $background_hex;
    matugen-surface: $surface_hex;
    matugen-foreground: $readable_text_hex;
    matugen-accent: $accent_hex;
    matugen-on-accent: $on_accent_hex;
    matugen-error: $error_hex;
}

window {
    background-color: @matugen-background;
    border-color: @matugen-accent;
}

mainbox,
listview,
inputbar {
    background-color: @matugen-background;
}

element {
    text-color: @matugen-foreground;
}

element normal normal,
element selected normal,
element alternate normal {
    text-color: @matugen-foreground;
}

element selected {
    background-color: @matugen-accent;
    text-color: @matugen-on-accent;
}

entry {
    text-color: @matugen-foreground;
}

prompt,
textbox-prompt-colon {
    text-color: @matugen-accent;
}
EOF

    if [ -f "$ROFI_CONFIG" ] && ! grep -qxF '@import "colors.rasi"' "$ROFI_CONFIG"; then
        printf '\n@import "colors.rasi"\n' >>"$ROFI_CONFIG"
    fi
}

write_gtk_theme() {
    local background_hex=$(color_hex "$BACKGROUND")
    local readable_text_hex=$(color_hex "$READABLE_TEXT")
    local surface_hex=$(color_hex "$SURFACE")
    local primary_hex=$(color_hex "$PRIMARY")
    local foreground_hex=$(color_hex "$FOREGROUND")

    for dir in "$GTK3_DIR" "$GTK4_DIR"; do
        mkdir -p "$dir"
        cat >"$dir/gtk.css" <<EOF
@define-color theme_bg_color $background_hex;
@define-color theme_fg_color $readable_text_hex;
@define-color theme_base_color $surface_hex;
@define-color theme_selected_bg_color $primary_hex;
@define-color theme_selected_fg_color $foreground_hex;
@define-color accent_color $primary_hex;
@define-color accent_bg_color $primary_hex;
@define-color accent_fg_color $foreground_hex;
EOF
        cp "$dir/gtk.css" "$dir/gtk-dark.css"
    done
}

write_wlogout_theme() {
    [ -d "$(dirname "$WLOGOUT_STYLE")" ] || return 0
    local bg_rgb surface_rgb accent_rgb
    local readable_hex foreground_hex primary_hex
    bg_rgb=$(hex_to_rgb_csv "$BACKGROUND")
    surface_rgb=$(hex_to_rgb_csv "$SURFACE")
    accent_rgb=$(hex_to_rgb_csv "$PRIMARY")
    readable_hex=$(color_hex "$READABLE_TEXT")
    foreground_hex=$(color_hex "$FOREGROUND")
    primary_hex=$(color_hex "$PRIMARY")

    cat >"$WLOGOUT_STYLE" <<EOF
* {
    font-family: "JetBrainsMono Nerd Font", "JetBrains Mono", sans-serif;
    font-size: 18px;
}

window {
    background-color: rgba($bg_rgb, 0.55);
}

button {
    margin: 10px;
    padding: 20px 28px;
    border-radius: 16px;
    border: 1px solid transparent;
    color: $readable_hex;
    background-color: rgba($surface_rgb, 0.7);
}

button:hover {
    border-color: $primary_hex;
    background-color: $primary_hex;
    color: rgba($bg_rgb, 1);
}
EOF
}

write_swaync_theme() {
    mkdir -p "$HOME/.config/swaync"
    mkdir -p "$HOME/.config/eww"
    local bg_rgb surface_rgb accent_rgb fg_rgb
    bg_rgb=$(hex_to_rgb_csv "$BACKGROUND")
    surface_rgb=$(hex_to_rgb_csv "$SURFACE")
    accent_rgb=$(hex_to_rgb_csv "$PRIMARY")
    fg_rgb=$(hex_to_rgb_csv "$READABLE_TEXT")

    # SwayNC colors
    cat >"$HOME/.config/swaync/colors.css" <<EOF
@define-color cc-bg rgba(${bg_rgb}, 0.85);
@define-color noti-border-color rgba(${accent_rgb}, 0.2);
@define-color noti-bg rgba(${surface_rgb}, 0.95);
@define-color noti-bg-opaque rgb(${surface_rgb});
@define-color noti-bg-darker rgb(${bg_rgb});
@define-color noti-bg-hover rgba(${accent_rgb}, 0.15);
@define-color noti-bg-focus rgba(${accent_rgb}, 0.25);
@define-color noti-close-bg rgba(${accent_rgb}, 0.16);
@define-color noti-close-bg-hover rgba(${accent_rgb}, 0.28);
@define-color text-color rgb(${fg_rgb});
@define-color text-color-disabled rgba(${fg_rgb}, 0.5);
@define-color bg-selected rgb(${accent_rgb});
EOF

    # Eww colors
    cat >"$HOME/.config/eww/colors.css" <<EOF
@define-color background rgb(${bg_rgb});
@define-color surface rgb(${surface_rgb});
@define-color primary rgb(${accent_rgb});
@define-color secondary rgb(${accent_rgb});
@define-color text rgb(${fg_rgb});
@define-color readable_text rgb(${fg_rgb});
@define-color error rgb(255, 100, 100);
@define-color success rgb(100, 255, 100);
EOF
}


hex_to_rgb_csv() {
    local input=$1
    local hex

    hex=${input#rgba(}
    hex=${hex%)}
    hex=${hex#\#}
    if [ "${#hex}" -eq 8 ]; then
        hex=${hex:0:6}
    fi
    printf '%d, %d, %d' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

# Apply theme
apply_theme() {
    local theme=$1
    local theme_file="$THEME_DIR/$theme.conf"

    if [ ! -f "$theme_file" ]; then
        echo "Error: Theme '$theme' not found in $THEME_DIR"
        return 1
    fi

    # Copy theme colors to colors.conf
    cp "$theme_file" "$COLORS_CONF"

    # Add metadata
    {
        echo ""
        echo "# Theme: $theme"
        echo "\$theme_name = $theme"
    } >> "$COLORS_CONF"

    # Extract colors
    local background=$(parse_color "background" "$theme_file")
    local surface=$(parse_color "surface" "$theme_file")
    local foreground=$(parse_color "foreground" "$theme_file")
    local readable_foreground=$(parse_color "readable_foreground" "$theme_file")
    local primary=$(parse_color "primary" "$theme_file")
    local secondary=$(parse_color "secondary" "$theme_file")
    local tertiary=$(parse_color "tertiary" "$theme_file")
    local accent=$(parse_color "accent" "$theme_file")
    local error=$(parse_color "error" "$theme_file")
    local success=$(parse_color "success" "$theme_file")
    local warning=$(parse_color "warning" "$theme_file")

    BACKGROUND="$background"
    SURFACE="$surface"
    FOREGROUND="$foreground"
    READABLE_TEXT="$readable_foreground"
    PRIMARY="$primary"
    SECONDARY="$secondary"
    TERTIARY="$tertiary"
    ACCENT="$accent"
    ERROR="$error"
    SUCCESS="$success"
    WARNING="$warning"
    SURFACE_CONTAINER="$surface"

    write_waybar_theme
    write_kitty_theme
    write_rofi_theme
    write_gtk_theme
    # write_wlogout_theme
    write_swaync_theme
    write_hyprlock_from_preset

    reload_waybar
    pkill -SIGUSR1 kitty 2>/dev/null || true
    swaync-client -rs 2>/dev/null || true

    # Save current theme
    echo "$theme" > "$CURRENT_THEME_FILE"

    # Reload Hyprland config (re-reads appearance.lua with new colors)
    hyprctl reload >/dev/null 2>&1 || true

    notify-send "Theme preset" "$theme" 2>/dev/null || true
    echo "Theme applied: $theme"
}

hyprlock_rgb_from_rgba() {
    local input=$1
    local hex
    hex=${input#rgba(}
    hex=${hex%)}
    hex=${hex:0:6}
    printf 'rgb(%d, %d, %d)' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
}

write_hyprlock_from_preset() {
    local bg_rgb fg_rgb accent_rgb surface_rgb tertiary_rgb dim_rgb
    bg_rgb=$(hyprlock_rgb_from_rgba "$BACKGROUND")
    fg_rgb=$(hyprlock_rgb_from_rgba "$READABLE_TEXT")
    accent_rgb=$(hyprlock_rgb_from_rgba "$PRIMARY")
    surface_rgb=$(hyprlock_rgb_from_rgba "$SURFACE_CONTAINER")
    tertiary_rgb=$(hyprlock_rgb_from_rgba "$TERTIARY")
    dim_rgb=$(hyprlock_rgb_from_rgba "$SECONDARY")

    cat >"$HOME/.config/hypr/hyprlock.conf" <<EOF
# Generated by theme-preset-switcher.sh

background {
    path = \$HOME/.config/hypr/current_wallpaper
    blur_size = 8
    blur_passes = 4
    contrast = 0.85
    brightness = 0.55
    vibrancy = 0.28
    vibrancy_darkness = 0.15
}

input-field {
    monitor =
    size = 320, 58
    outline_thickness = 3
    dots_size = 0.28
    dots_spacing = 0.45
    dots_center = true
    outer_color = $accent_rgb
    inner_color = $surface_rgb
    font_color = $fg_rgb
    fade_on_empty = true
    placeholder_text = Enter password
    hide_input = false
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date '+%H:%M'
    color = $fg_rgb
    font_size = 88
    font_family = JetBrainsMono Nerd Font
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date '+%A · %d %B'
    color = $dim_rgb
    font_size = 17
    font_family = JetBrainsMono Nerd Font
    position = 0, 55
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "\$(whoami)@\$(hostname -s)"
    color = $tertiary_rgb
    font_size = 15
    font_family = JetBrainsMono Nerd Font
    position = 0, 20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:30000] echo "󰁹  \$(cat /sys/class/power_supply/BAT1/capacity 2>/dev/null || echo '—')%"
    color = $dim_rgb
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, -20
    halign = center
    valign = center
}
EOF
}

reload_waybar() {
    pkill -SIGUSR2 waybar 2>/dev/null || {
        pkill waybar 2>/dev/null || true
        waybar >/dev/null 2>&1 &
    }
}

# Show theme picker UI
show_picker() {
    local themes=($(list_themes))
    local current=$(get_current_theme)
    local selected

    if command -v rofi >/dev/null 2>&1; then
        local -a displays=()
        for theme in "${themes[@]}"; do
            local theme_file="$THEME_DIR/$theme.conf"
            local primary=$(parse_color "primary" "$theme_file")
            local accent=$(parse_color "accent" "$theme_file")
            local background=$(parse_color "background" "$theme_file")
            
            local p_hex=$(color_hex "$primary")
            local a_hex=$(color_hex "$accent")
            local b_hex=$(color_hex "$background")
            
            local color_info="<span foreground=\"$p_hex\">■</span><span foreground=\"$a_hex\">■</span><span foreground=\"$b_hex\">■</span>"
            displays+=("$(printf '%-20s %s' "$theme" "$color_info")")
        done
        local selected_index
        selected_index=$(printf '%s\n' "${displays[@]}" | rofi -dmenu -i -p "Select Theme" -markup-rows -format i) || return 1
        [[ "$selected_index" =~ ^[0-9]+$ ]] || return 1
        selected="${themes[$selected_index]}"
    elif command -v fzf >/dev/null 2>&1 && [ -t 0 ]; then
        selected=$(printf '%s\n' "${themes[@]}" | fzf --prompt="Theme> " --height=40% --reverse --border)
    else
        echo "Available themes:"
        for i in "${!themes[@]}"; do
            printf "%d) %s%s\n" $((i+1)) "${themes[$i]}" "$([ "${themes[$i]}" = "$current" ] && echo ' (current)' || echo '')"
        done
        read -p "Select theme (number or name): " selected
    fi

    [ -n "$selected" ] && apply_theme "$selected"
}

main() {
    case "${1:-}" in
        list)
            echo "Available themes:"
            for theme in $(list_themes); do
                current=$(get_current_theme)
                [ "$theme" = "$current" ] && echo "  ✓ $theme" || echo "    $theme"
            done
            ;;
        current)
            get_current_theme
            ;;
        apply)
            [ -z "${2:-}" ] && { echo "Usage: $0 apply <theme>"; exit 1; }
            apply_theme "$2"
            ;;
        *)
            show_picker
            ;;
    esac
}

main "$@"
