# Synthwave 84 - Retro neon cyberpunk sunset
$background = rgba(241b38ff)
$surface = rgba(342556ff)
$foreground = rgba(d7bde2ff)
$readable_foreground = rgba(f4eef9ff)
$primary = rgba(ff7edbff)
$secondary = rgba(36f9f6ff)
$tertiary = rgba(f6a2ffff)
$error = rgba(fe4450ff)
$accent = rgba(ff7edbff)
$success = rgba(36f9f6ff)
$warning = rgba(fecd5eff)
