# Paper Color - Soothing paper-like light theme
$background = rgba(eeeeeeff)
$surface = rgba(d0d0d0ff)
$foreground = rgba(444444ff)
$readable_foreground = rgba(222222ff)
$primary = rgba(2f5fafff)
$secondary = rgba(5f8700ff)
$tertiary = rgba(af5fafff)
$error = rgba(d70000ff)
$accent = rgba(2f5fafff)
$success = rgba(5f8700ff)
$warning = rgba(af8700ff)
